- name: Configure nginx web root folder in Ubuntu
  copy: src=ubuntu_default dest=/etc/nginx/sites-available/default
  when:  ansible_distribution == "Ubuntu"

- name: Configure nginx web root folder in CentOS 
  copy: src=centos_default.conf dest=/etc/nginx/conf.d/default.conf
  when:  ansible_distribution == "CentOS"
