---
# handlers file for nginx
- name: Restart nginx in Ubuntu
  shell: "/etc/init.d/nginx restart"
  when: ( ansible_os_family == "Debian" and ansible_distribution == "Ubuntu" )

- name: Restart nginx in CentOS 
  service: name=nginx state=restarted
  when: ( ansible_os_family == "RedHat" and ansible_distribution == "CentOS" )
